### ISSUE TITLE
alteryx gallery api username and password

### ISSUE THREAD

**Issue by ZinatWali** [icarr-ayx/alteryx-gallery-api#1]
Alteryx gallery api requires api key and secret key. Why is the api client based on username and password? Also, there is no doc for pre-auth in Alteryx gallery api doc.

**Comment by johnkabler** [comment]
Zinat,

The API you are speaking of is the official, public Alteryx Gallery API.  The API that this library is targeted at is the private API, which is not guaranteed to be free of breaking changes.  

Thanks,

JP
