### ISSUE TITLE
Use of login function in open source project

### ISSUE THREAD

**Issue by RossK1** [icarr-ayx/alteryx-gallery-api#2]
@icarr 

Found this code 6 years later and very glad I did. Authentication against the Alteryx Gallery front-end is certainly not a trivial matter.
I don't see any license attached to this repo though. Would it be ok with you if I rework the login function to work with the latest version of the Gallery and use it in my project?

Thanks :)

**Comment by icarr** [comment]
Hi @RossK1  - 

I just added an MIT license to the repo.  Feel free to use the code in your project.

-Ian

**Comment by RossK1** [comment]
Thanks, @icarr :)
